# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614095717 on 2016-07-01 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hasta', '0002_auto_20160701_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muayene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muayene_tarihi', models.DateField()),
                ('yakinma', models.TextField(blank=True, null=True)),
                ('kullandigi_ilaclar', models.TextField(blank=True, null=True)),
                ('muayene', models.TextField(blank=True, null=True)),
                ('istenen_tetkikler', models.TextField(blank=True, null=True)),
                ('tetkik_sonuclari', models.TextField(blank=True, null=True)),
                ('öntani_tani', models.TextField(blank=True, null=True)),
                ('öneri_görüsler', models.TextField(blank=True, null=True)),
                ('özel_notlar', models.TextField(blank=True, null=True)),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hasta.Hasta')),
            ],
        ),
    ]
