# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muayene', '0012_auto_20160720_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratuvaristek',
            name='tarih',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='tarih',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='tarih',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recete',
            name='tarih',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
