# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muayene', '0021_auto_20160814_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilac',
            name='bilgi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ilac',
            name='kullanim',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
