# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muayene', '0030_auto_20160831_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muayene',
            name='kullandigi_ilaclar',
        ),
        migrations.AddField(
            model_name='muayene',
            name='kullandigi_ilaclar',
            field=models.TextField(blank=True, default=' ', max_length=512),
        ),
    ]
