# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muayene', '0022_auto_20160814_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilac',
            name='bilgi',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='ilac',
            name='kullanim',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='laboratuvaristek',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='baki',
            field=models.TextField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='oneri_gorusler',
            field=models.TextField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='ontani_tani',
            field=models.TextField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='ozel_notlar',
            field=models.TextField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='yakinma',
            field=models.TextField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='tani',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='recete',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
