# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_ilac_fields(apps, schema_editor):
    Recete = apps.get_model('muayene', 'Recete')
    ReceteIlac = apps.get_model('muayene', 'ReceteIlac')
    for recete in Recete.objects.all():
        recete_ilac = ReceteIlac.objects.create(ilac=recete.ilac1, kullanim=recete.ilac1_kullanim, kutu=recete.ilac1_kutu)
        recete.ilaclar.add(recete_ilac)

        if recete.ilac2:
            recete_ilac = ReceteIlac.objects.create(ilac=recete.ilac2, kullanim=recete.ilac2_kullanim, kutu=recete.ilac2_kutu)
            recete.ilaclar.add(recete_ilac)
        if recete.ilac3:
            recete_ilac = ReceteIlac.objects.create(ilac=recete.ilac3, kullanim=recete.ilac3_kullanim, kutu=recete.ilac3_kutu)
            recete.ilaclar.add(recete_ilac)
        if recete.ilac4:
            recete_ilac = ReceteIlac.objects.create(ilac=recete.ilac4, kullanim=recete.ilac4_kullanim, kutu=recete.ilac4_kutu)
            recete.ilaclar.add(recete_ilac)
        if recete.ilac5:
            recete_ilac = ReceteIlac.objects.create(ilac=recete.ilac5, kullanim=recete.ilac5_kullanim, kutu=recete.ilac5_kutu)
            recete.ilaclar.add(recete_ilac)


class Migration(migrations.Migration):

    dependencies = [
        ('muayene', '0034_auto_20161004_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceteIlac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim', models.CharField(max_length=30)),
                ('kutu', models.IntegerField(default=1)),
                ('ilac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muayene.Ilac')),
            ],
        ),
        migrations.AlterField(
            model_name='muayene',
            name='baki',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='kullandigi_ilaclar',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='oneri_gorusler',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='ontani_tani',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='ozel_notlar',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='muayene',
            name='yakinma',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='tani',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='recete',
            name='ilaclar',
            field=models.ManyToManyField(to='muayene.ReceteIlac'),
        ),
        migrations.RunPython(migrate_ilac_fields)
    ]
