# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muayene', '0035_auto_20170818_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recete',
            name='ilac1',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac1_kullanim',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac1_kutu',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac2',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac2_kullanim',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac2_kutu',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac3',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac3_kullanim',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac3_kutu',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac4',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac4_kullanim',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac4_kutu',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac5',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac5_kullanim',
        ),
        migrations.RemoveField(
            model_name='recete',
            name='ilac5_kutu',
        ),
    ]
