language: python
python:
    - "3.5"
install: "pip install -r requirements.txt"
before_script: "cat /dev/urandom | tr -cd 'a-zA-Z0-9' | fold -w 128 | head -n 1 | sudo tee /etc/secret"
script: "python src/manage.py test"
