# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0031_hasta_ahsevk_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesme',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
