# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0002_randevu_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='contact_phone',
            field=models.CharField(max_length=13, verbose_name='İletişim'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='hasta',
            field=models.CharField(max_length=64, verbose_name='Hasta'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='person_number',
            field=models.IntegerField(verbose_name='Kişi sayısı'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='time',
            field=models.TimeField(verbose_name='Saat'),
        ),
    ]
