# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614095717 on 2016-07-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasta',
            name='adres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='ah_police_no',
            field=models.BigIntegerField(default='000000'),
        ),
        migrations.AddField(
            model_name='hasta',
            name='alkol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='boy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='cep_telefon',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='cinsiyet',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='hasta',
            name='cocuk1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='cocuk2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='cocuk3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='eposta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='es_ad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='es_meslek',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='ev_telefon',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='is_telefon',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='kilo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='meslek',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='ozgecmis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='semt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='sigara',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hasta',
            name='soygecmis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
