# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0007_auto_20160719_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasta',
            name='ah_police_no',
        ),
        migrations.AddField(
            model_name='hasta',
            name='sigorta',
            field=models.CharField(choices=[('ALZ', 'Allianz'), ('ALZKUR', 'Allianz Kurumsal'), ('EU', 'Euroka'), ('GRP', 'Groupama'), ('MPF', 'Mappfre'), ('AK', 'Ak Sigorta'), ('ACB', 'Acıbadem'), ('CP', 'Check-up')], default='ALZ', max_length=30),
        ),
    ]
