# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0013_auto_20160801_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasta',
            name='aile',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='hasta.Aile'),
        ),
    ]
