# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0016_auto_20160814_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasta',
            name='dogum_tarihi',
            field=models.DateField(default=datetime.datetime(2016, 8, 14, 14, 2, 10, 657918, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
