# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0023_auto_20160822_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasta',
            name='boy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='kilo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
