# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0030_auto_20160831_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasta',
            name='ahsevk_done',
            field=models.BooleanField(default=False),
        ),
    ]
