# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0003_auto_20160702_2048"),
    ]

    operations = [
        migrations.AddField(
            model_name="hasta",
            name="dogum_tarihi",
            field=models.DateField(blank=True, null=True),
        ),
    ]
