# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0004_hasta_dogum_tarihi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soyad", models.CharField(max_length=30)),
                ("uyeler", models.ManyToManyField(to="hasta.Hasta")),
            ],
        ),
    ]
