# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0005_aile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aile",
            name="uyeler",
        ),
        migrations.AddField(
            model_name="hasta",
            name="aile",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="hasta.Aile"
            ),
        ),
    ]
