# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0006_auto_20160713_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="ah_police_no",
            field=models.BigIntegerField(
                choices=[
                    ("ALZ", "Allianz"),
                    ("ALZKUR", "Allianz Kurumsal"),
                    ("EU", "Euroka"),
                    ("GRP", "Groupama"),
                    ("MPF", "Mappfre"),
                    ("AK", "Ak Sigorta"),
                    ("ACB", "Acıbadem"),
                    ("CP", "Check-up"),
                ],
                default="ALZ",
            ),
        ),
    ]
