# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0008_auto_20160719_2252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="cinsiyet",
            field=models.CharField(
                choices=[("K", "Kadın"), ("E", "Erkek")], default="K", max_length=5
            ),
        ),
    ]
