# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0011_sozlesme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sozlesme",
            name="sure",
        ),
        migrations.AddField(
            model_name="sozlesme",
            name="baslangic_tarihi",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
