# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0015_auto_20160814_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasta',
            name='boy',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hasta',
            name='kilo',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
