# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0018_auto_20160819_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasta',
            name='aile',
        ),
        migrations.AlterField(
            model_name='hasta',
            name='adres',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='alkol',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='boy',
            field=models.CharField(blank=True, default=' ', max_length=5),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='cep_telefon',
            field=models.CharField(blank=True, default=' ', max_length=13),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('K', 'Kadın'), ('E', 'Erkek')], default='K', max_length=5),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='cocuk1',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='cocuk2',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='cocuk3',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='eposta',
            field=models.EmailField(blank=True, default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='es_ad',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='es_meslek',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='ev_telefon',
            field=models.CharField(blank=True, default=' ', max_length=13),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='is_telefon',
            field=models.CharField(blank=True, default=' ', max_length=13),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='kayit_tarihi',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='kilo',
            field=models.CharField(blank=True, default=' ', max_length=5),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='meslek',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='ozgecmis',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='semt',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='sigara',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='sigorta',
            field=models.CharField(blank=True, choices=[('ALZ', 'Allianz'), ('ALZKUR', 'Allianz Kurumsal'), ('EU', 'Euroka'), ('GRP', 'Groupama'), ('MPF', 'Mappfre'), ('AK', 'Ak Sigorta'), ('ACB', 'Acıbadem'), ('CP', 'Check-up')], default='ALZ', max_length=30),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='soygecmis',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='hasta',
            name='tc_kimlik_no',
            field=models.CharField(blank=True, default=' ', max_length=11),
        ),
        migrations.DeleteModel(
            name='Aile',
        ),
    ]
