# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0021_auto_20160819_2032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="boy",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="hasta",
            name="kilo",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
