# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0026_auto_20160830_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="tc_kimlik_no",
            field=models.CharField(
                blank=True, default=" ", max_length=11, null=True, unique=True
            ),
        ),
    ]
