# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0027_auto_20160830_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="tc_kimlik_no",
            field=models.CharField(blank=True, default=" ", max_length=11, null=True),
        ),
    ]
