# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0029_auto_20160830_2235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasta",
            name="boy",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="hasta",
            name="kilo",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
