# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-31 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0035_auto_20170723_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasta',
            name='dogum_yeri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
