# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-31 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasta", "0036_hasta_dogum_yeri"),
    ]

    operations = [
        migrations.AddField(
            model_name="hasta",
            name="uyruk",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
