# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasta', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('person_number', models.IntegerField()),
                ('contact_phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='randevu',
            unique_together=set([('date', 'time')]),
        ),
    ]
