# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randevu", "0003_auto_20170809_2313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="randevu",
            name="state",
            field=models.SmallIntegerField(choices=[(1, "Açık"), (2, "İptal")]),
        ),
    ]
