# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("randevu", "0005_auto_20170818_2112"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="randevu",
            unique_together=set([]),
        ),
    ]
