# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614095717 on 2016-07-07 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0002_auto_20160707_2111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muayene",
            name="muayene_tarihi",
            field=models.DateField(
                default=datetime.datetime(2016, 7, 7, 18, 14, 9, 669721, tzinfo=utc)
            ),
        ),
    ]
