# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614095717 on 2016-07-07 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muayene', '0004_auto_20160707_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muayene',
            name='muayene_tarihi',
            field=models.DateField(default=datetime.date(2016, 7, 7)),
        ),
    ]
