# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614095717 on 2016-07-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0006_auto_20160708_1652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muayene",
            name="muayene_tarihi",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
