# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0010_auto_20160711_2314"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rapor",
            old_name="rapor_gun",
            new_name="gun",
        ),
    ]
