# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0015_auto_20160725_2312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muayene",
            name="kullandigi_ilaclar",
            field=models.ManyToManyField(blank=True, to="muayene.Ilac"),
        ),
    ]
