# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0017_auto_20160726_2303"),
    ]

    operations = [
        migrations.RenameField(
            model_name="muayene",
            old_name="muayene",
            new_name="foobarbaz",
        ),
    ]
