# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0018_auto_20160731_1436"),
    ]

    operations = [
        migrations.RenameField(
            model_name="muayene",
            old_name="foobarbaz",
            new_name="baki",
        ),
    ]
