# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0020_auto_20160809_2338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muayene",
            name="tarih",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
