# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0025_auto_20160823_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="laboratuvaristek",
            name="aclik_insulin",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="aclik_insulin_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="aclik_kan",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="aclik_kan_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="alp",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="alp_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="alt_batin",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="alt_batin_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="anti_tg",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="anti_tg_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="anti_tpo",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="anti_tpo_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="aso",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="aso_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="b12",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="b12_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="bogaz_kab",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="bogaz_kab_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="crp",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="crp_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="eforlu_ekg",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="eforlu_ekg_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ejaculat_kab",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ejaculat_kab_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ekg",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ekg_holter",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ekg_holter_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ekg_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ekokardiografi",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ekokardiografi_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ferritin",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ferritin_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="folik_asit",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="folik_asit_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="free_psa",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="free_psa_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="free_t3",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="free_t3_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="free_t4",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="free_t4_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="gaita",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="gaita_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ggt",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ggt_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="hba1c",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="hba1c_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="hdl",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="hdl_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="hemoglobin",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="hemoglobin_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="hemogram",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="hemogram_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="idrar_kab",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="idrar_kab_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ikiyonlu_lsv",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ikiyonlu_lsv_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ikiyonlu_servikal",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ikiyonlu_servikal_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="kreatinin",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="kreatinin_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ldl",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ldl_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="meme",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="meme_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="og11",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="og11_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="pa_akciger",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="pa_akciger_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="psa",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="psa_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="rf",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="rf_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="sedim",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="sedim_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="serum_demir",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="serum_demir_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="sgot",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="sgot_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="sgpt",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="sgpt_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tam_idrar",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tam_idrar_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tansiyon_holter",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tansiyon_holter_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tdbk",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tdbk_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tiroid",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tiroid_sintigrafi",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tiroid_sintigrafi_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tiroid_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tokluk_kan",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tokluk_kan_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="total_kolesterol",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="total_kolesterol_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="trigliserit",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="trigliserit_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tsh",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tsh_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tum_batin",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="tum_batin_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ure",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ure_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="urik_asit",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="urik_asit_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="uriner",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="uriner_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ust_batin",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="ust_batin_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="waters",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="waters_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="yirmibesohd",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="yirmibesohd_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="yuzyirmi_insulin",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="laboratuvaristek",
            name="yuzyirmi_insulin_sonuc",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
    ]
