# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0026_auto_20160823_1506"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="aclik_insulin",
            field=models.BooleanField(default=False, verbose_name="Açlık İnsülin"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="aclik_kan",
            field=models.BooleanField(default=False, verbose_name="Açlık Kan Şekeri"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="alp",
            field=models.BooleanField(default=False, verbose_name="ALP"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="alt_batin",
            field=models.BooleanField(default=False, verbose_name="Alt Batın US"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="anti_tg",
            field=models.BooleanField(default=False, verbose_name="anti-TG"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="anti_tpo",
            field=models.BooleanField(default=False, verbose_name="anti-TPO"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="aso",
            field=models.BooleanField(default=False, verbose_name="ASO"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="b12",
            field=models.BooleanField(default=False, verbose_name="B-12"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="bogaz_kab",
            field=models.BooleanField(default=False, verbose_name="Boğaz KAB"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="crp",
            field=models.BooleanField(default=False, verbose_name="CRP"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="eforlu_ekg",
            field=models.BooleanField(default=False, verbose_name="Eforlu EKG"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ejaculat_kab",
            field=models.BooleanField(default=False, verbose_name="Ejaculat KAB"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ekg",
            field=models.BooleanField(default=False, verbose_name="EKG"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ekg_holter",
            field=models.BooleanField(default=False, verbose_name="EKG Holter"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ekokardiografi",
            field=models.BooleanField(default=False, verbose_name="Ekokardiografi"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ferritin",
            field=models.BooleanField(default=False, verbose_name="Ferritin"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="folik_asit",
            field=models.BooleanField(default=False, verbose_name="Folik asit"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="free_psa",
            field=models.BooleanField(default=False, verbose_name="Free PSA"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="free_t3",
            field=models.BooleanField(default=False, verbose_name="Free T3"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="free_t4",
            field=models.BooleanField(default=False, verbose_name="Free T4"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="gaita",
            field=models.BooleanField(
                default=False, verbose_name="Gaita Direkt Bakısı"
            ),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ggt",
            field=models.BooleanField(default=False, verbose_name="GGT"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="hba1c",
            field=models.BooleanField(default=False, verbose_name="HbA1c"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="hdl",
            field=models.BooleanField(default=False, verbose_name="HDL"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="hemoglobin",
            field=models.BooleanField(
                default=False, verbose_name="Hemoglobin Elektroforezi"
            ),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="hemogram",
            field=models.BooleanField(default=False, verbose_name="Hemogram"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="idrar_kab",
            field=models.BooleanField(default=False, verbose_name="İdrar KAB"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ikiyonlu_lsv",
            field=models.BooleanField(
                default=False, verbose_name="2 Yönlü LSV Grafisi"
            ),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ikiyonlu_servikal",
            field=models.BooleanField(
                default=False, verbose_name="2 Yönlü Servikal Grafisi"
            ),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="kreatinin",
            field=models.BooleanField(default=False, verbose_name="Kreatinin"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ldl",
            field=models.BooleanField(default=False, verbose_name="LDL"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="meme",
            field=models.BooleanField(default=False, verbose_name="Meme US"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="og11",
            field=models.BooleanField(
                default=False,
                verbose_name="OG11 (75 gr Glikoz ile 0-60-120-180 dakikalarda)",
            ),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="pa_akciger",
            field=models.BooleanField(default=False, verbose_name="PA Akciğer Grafisi"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="psa",
            field=models.BooleanField(default=False, verbose_name="PSA"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="rf",
            field=models.BooleanField(default=False, verbose_name="RF"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="sedim",
            field=models.BooleanField(default=False, verbose_name="Sedim"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="serum_demir",
            field=models.BooleanField(default=False, verbose_name="Serum Demir"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="sgot",
            field=models.BooleanField(default=False, verbose_name="SGOT (AST)"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="sgpt",
            field=models.BooleanField(default=False, verbose_name="SGPT (ALT)"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="tam_idrar",
            field=models.BooleanField(default=False, verbose_name="Tam İdrar"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="tansiyon_holter",
            field=models.BooleanField(default=False, verbose_name="Tansiyon Holter"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="tdbk",
            field=models.BooleanField(default=False, verbose_name="TDBK"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="tiroid",
            field=models.BooleanField(default=False, verbose_name="Tiroid US"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="tiroid_sintigrafi",
            field=models.BooleanField(
                default=False, verbose_name="Tiroid Sintigrafisi"
            ),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="tokluk_kan",
            field=models.BooleanField(default=False, verbose_name="Tokluk Kan Şekeri"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="total_kolesterol",
            field=models.BooleanField(default=False, verbose_name="Total Kolesterol"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="trigliserit",
            field=models.BooleanField(default=False, verbose_name="Trigliserit"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="tsh",
            field=models.BooleanField(default=False, verbose_name="TSH"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="tum_batin",
            field=models.BooleanField(default=False, verbose_name="Tüm Batın US"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ure",
            field=models.BooleanField(default=False, verbose_name="Üre"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="urik_asit",
            field=models.BooleanField(default=False, verbose_name="Ürik asit"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="uriner",
            field=models.BooleanField(default=False, verbose_name="Üriner US"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="ust_batin",
            field=models.BooleanField(default=False, verbose_name="Üst Batın US"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="waters",
            field=models.BooleanField(default=False, verbose_name="Waters Grafisi"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="yirmibesohd",
            field=models.BooleanField(default=False, verbose_name="25 OH D3"),
        ),
        migrations.AlterField(
            model_name="laboratuvaristek",
            name="yuzyirmi_insulin",
            field=models.BooleanField(default=False, verbose_name="120 dk İnsülin"),
        ),
    ]
