# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0029_muayenerelatedfile_yaratim_tarihi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilac",
            name="bilgi",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="ilac",
            name="kullanim",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
