# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0031_auto_20160919_2015"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuayeneAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shorthand", models.CharField(max_length=10)),
                ("longhand", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="muayene",
            options={"get_latest_by": "tarih"},
        ),
    ]
