# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0032_auto_20160922_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muayenealias",
            name="shorthand",
            field=models.CharField(max_length=30),
        ),
    ]
