# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muayene", "0034_auto_20161004_1131"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ilac",
            options={"verbose_name": "İlaç", "verbose_name_plural": "İlaçlar"},
        ),
        migrations.AlterModelOptions(
            name="laboratuvaristek",
            options={
                "verbose_name": "Laboratuvar Istek",
                "verbose_name_plural": "Laboratuvar Istekleri",
            },
        ),
        migrations.AlterModelOptions(
            name="muayene",
            options={
                "get_latest_by": "tarih",
                "verbose_name": "Muayene",
                "verbose_name_plural": "Muayeneler",
            },
        ),
        migrations.AlterModelOptions(
            name="rapor",
            options={"verbose_name": "Rapor", "verbose_name_plural": "Raporlar"},
        ),
        migrations.AlterModelOptions(
            name="recete",
            options={"verbose_name": "Reçete", "verbose_name_plural": "Reçeteler"},
        ),
    ]
