# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_laboratuvar_fields(apps, schema_editor):
    Laboratuvar = apps.get_model('muayene', 'Laboratuvar')
    Tetkik = apps.get_model('muayene', 'Tetkik')
    LaboratuvarIstek = apps.get_model('muayene', 'LaboratuvarIstek')

    for lab_istek in LaboratuvarIstek.objects.all():
        if lab_istek.hemogram:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('hemogram').verbose_name)
            sonuc = lab_istek.hemogram_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.sedim:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('sedim').verbose_name)
            sonuc = lab_istek.sedim_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.serum_demir:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('serum_demir').verbose_name)
            sonuc = lab_istek.serum_demir_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.tdbk:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('tdbk').verbose_name)
            sonuc = lab_istek.tdbk_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ferritin:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ferritin').verbose_name)
            sonuc = lab_istek.ferritin_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.b12:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('b12').verbose_name)
            sonuc = lab_istek.b12_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.folik_asit:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('folik_asit').verbose_name)
            sonuc = lab_istek.folik_asit_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.hemoglobin:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('hemoglobin').verbose_name)
            sonuc = lab_istek.hemoglobin_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.aclik_kan:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('aclik_kan').verbose_name)
            sonuc = lab_istek.aclik_kan_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.tokluk_kan:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('tokluk_kan').verbose_name)
            sonuc = lab_istek.tokluk_kan_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.hba1c:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('hba1c').verbose_name)
            sonuc = lab_istek.hba1c_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.sgot:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('sgot').verbose_name)
            sonuc = lab_istek.sgot_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.sgpt:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('sgpt').verbose_name)
            sonuc = lab_istek.sgpt_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ggt:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ggt').verbose_name)
            sonuc = lab_istek.ggt_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.alp:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('alp').verbose_name)
            sonuc = lab_istek.alp_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ure:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ure').verbose_name)
            sonuc = lab_istek.ure_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.kreatinin:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('kreatinin').verbose_name)
            sonuc = lab_istek.kreatinin_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.urik_asit:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('urik_asit').verbose_name)
            sonuc = lab_istek.urik_asit_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.total_kolesterol:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('total_kolesterol').verbose_name)
            sonuc = lab_istek.total_kolesterol_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.hdl:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('hdl').verbose_name)
            sonuc = lab_istek.hdl_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.trigliserit:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('trigliserit').verbose_name)
            sonuc = lab_istek.trigliserit_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ldl:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ldl').verbose_name)
            sonuc = lab_istek.ldl_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.free_t3:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('free_t3').verbose_name)
            sonuc = lab_istek.free_t3_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.free_t4:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('free_t4').verbose_name)
            sonuc = lab_istek.free_t4_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.tsh:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('tsh').verbose_name)
            sonuc = lab_istek.tsh_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.anti_tpo:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('anti_tpo').verbose_name)
            sonuc = lab_istek.anti_tpo_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.anti_tg:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('anti_tg').verbose_name)
            sonuc = lab_istek.anti_tg_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.aso:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('aso').verbose_name)
            sonuc = lab_istek.aso_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.crp:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('crp').verbose_name)
            sonuc = lab_istek.crp_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.rf:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('rf').verbose_name)
            sonuc = lab_istek.rf_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.psa:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('psa').verbose_name)
            sonuc = lab_istek.psa_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.free_psa:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('free_psa').verbose_name)
            sonuc = lab_istek.free_psa_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.tam_idrar:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('tam_idrar').verbose_name)
            sonuc = lab_istek.tam_idrar_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.idrar_kab:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('idrar_kab').verbose_name)
            sonuc = lab_istek.idrar_kab_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.gaita:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('gaita').verbose_name)
            sonuc = lab_istek.gaita_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.bogaz_kab:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('bogaz_kab').verbose_name)
            sonuc = lab_istek.bogaz_kab_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ejaculat_kab:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ejaculat_kab').verbose_name)
            sonuc = lab_istek.ejaculat_kab_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ekg:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ekg').verbose_name)
            sonuc = lab_istek.ekg_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.eforlu_ekg:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('eforlu_ekg').verbose_name)
            sonuc = lab_istek.eforlu_ekg_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ekokardiografi:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ekokardiografi').verbose_name)
            sonuc = lab_istek.ekokardiografi_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.tansiyon_holter:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('tansiyon_holter').verbose_name)
            sonuc = lab_istek.tansiyon_holter_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ekg_holter:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ekg_holter').verbose_name)
            sonuc = lab_istek.ekg_holter_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.pa_akciger:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('pa_akciger').verbose_name)
            sonuc = lab_istek.pa_akciger_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.waters:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('waters').verbose_name)
            sonuc = lab_istek.waters_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ikiyonlu_servikal:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ikiyonlu_servikal').verbose_name)
            sonuc = lab_istek.ikiyonlu_servikal_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ikiyonlu_lsv:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ikiyonlu_lsv').verbose_name)
            sonuc = lab_istek.ikiyonlu_lsv_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.tum_batin:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('tum_batin').verbose_name)
            sonuc = lab_istek.tum_batin_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.ust_batin:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('ust_batin').verbose_name)
            sonuc = lab_istek.ust_batin_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.alt_batin:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('alt_batin').verbose_name)
            sonuc = lab_istek.alt_batin_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.uriner:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('uriner').verbose_name)
            sonuc = lab_istek.uriner_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.tiroid:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('tiroid').verbose_name)
            sonuc = lab_istek.tiroid_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.meme:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('meme').verbose_name)
            sonuc = lab_istek.meme_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.tiroid_sintigrafi:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('tiroid_sintigrafi').verbose_name)
            sonuc = lab_istek.tiroid_sintigrafi_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.aclik_insulin:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('aclik_insulin').verbose_name)
            sonuc = lab_istek.aclik_insulin_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.yuzyirmi_insulin:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('yuzyirmi_insulin').verbose_name)
            sonuc = lab_istek.yuzyirmi_insulin_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.yirmibesohd:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('yirmibesohd').verbose_name)
            sonuc = lab_istek.yirmibesohd_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.og11:
            lab = Laboratuvar.objects.get_or_create(ad=LaboratuvarIstek._meta.get_field('og11').verbose_name)
            sonuc = lab_istek.og11_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.custom1:
            lab = Laboratuvar.objects.get_or_create(ad=lab_istek.custom1_ad)
            sonuc = lab_istek.custom1_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.custom2:
            lab = Laboratuvar.objects.get_or_create(ad=lab_istek.custom2_ad)
            sonuc = lab_istek.custom2_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.custom3:
            lab = Laboratuvar.objects.get_or_create(ad=lab_istek.custom3_ad)
            sonuc = lab_istek.custom3_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.custom4:
            lab = Laboratuvar.objects.get_or_create(ad=lab_istek.custom4_ad)
            sonuc = lab_istek.custom4_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)
        if lab_istek.custom5:
            lab = Laboratuvar.objects.get_or_create(ad=lab_istek.custom5_ad)
            sonuc = lab_istek.custom5_sonuc
            tetkik = Tetkik.objects.create(laboratuvar=lab[0], sonuc=sonuc)
            lab_istek.tetkikler.add(tetkik)


class Migration(migrations.Migration):

    dependencies = [
        ('muayene', '0036_auto_20170818_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tetkik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonuc', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratuvar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muayene.Laboratuvar')),
            ],
        ),
        migrations.AddField(
            model_name='laboratuvaristek',
            name='tetkikler',
            field=models.ManyToManyField(to='muayene.Tetkik'),
        ),
        migrations.RunPython(migrate_laboratuvar_fields)
    ]
