---
- name: Restore DB and media backups from S3
  hosts: all
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    HOME: /home/hastatakip
    BACKUP_DIR: /home/hastatakip/backups
    DB_DIR: /home/hastatakip/db
    MEDIA_BACKUP_NAME: "media.tar.gz"
    MEDIA_BACKUP_DEST: "{{ BACKUP_DIR }}/{{ MEDIA_BACKUP_NAME }}"
    BUCKET_NAME: hastatakip
  tasks:
    - name: Download from S3
      aws_s3:
        bucket: "{{ BUCKET_NAME }}"
        mode: get
        object: "{{ item.name }}"
        dest: "{{ item.dest }}"
      with_items:
        - { dest: "{{ MEDIA_BACKUP_DEST }}", name: "{{ MEDIA_BACKUP_NAME }}" }
        - { dest: "{{ DB_DIR }}/db.sqlite3", name: "latest.sqlite3" }
    - name: Decrypt backups
      command: ccrypt --force -E CCRYPT_KEYWORD -d "{{ item }}"
      with_items:
        - "{{ MEDIA_BACKUP_DEST }}"
        - "{{ DB_DIR }}/db.sqlite3"
    - name: Extract backups
      unarchive:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "{{ MEDIA_BACKUP_DEST }}", dest: "{{ HOME }}" }
